### ISSUE TITLE
tags module A::B

### ISSUE THREAD

**Issue by benoittgt** [tmm1/ripper-tags#30]
Hello

Does anyone know a way to found the ctags of a function define in a module.

I have this in a controller

```ruby
  def add_user
    respond_to do |format|
      format.js do
        @group.add_user @user
      end
    end
  end
```

when searching the tag of `.add_user` it jump to first line but, add_user is define in a module.

```ruby
module Abstracts::GroupRolesManagement
  def add_user user
     ...
  end
end
```

Trying with ripper tags doesn't solve my issue.

Thanks in advance

**Comment by mislav** [comment]
I'm assuming that you use vim to jump to a tag. Between multiple matches, Vim will find the "closest" tag and jump to it. In your case, you define `add_user` in the controller, so when you jump to `add_user` from that controller, the local function definition will always "win" over the one in another file. This is expected behavior from vim.

What you need is to get the editor to show you a list of matching tags so you can pick the one that you know is the canonical definition of the method (inside the GroupRolesManagement module). To do that, use <kbd>g Ctrl-]</kbd> or `:tsel <tagname>`.

**Comment by benoittgt** [comment]
Thanks @mislav
