### ISSUE TITLE
Index nested class / modules

### ISSUE THREAD

**Issue by lowski** [tmm1/ripper-tags#48]
It's more of a question rather than an issue because I'm not sure if it's bug or limitation of ctags.

If I have a class defined like this:

```ruby
class A::B

end
```

When I create tag file, there is entry for `B` class so if I highlight `A::B` in vim (in some other file), and try to jump to definition in vim it can not found it. It works only if I select `B`.

**Comment by WojtekKruszewski** [comment]
+1

Fortunately my tests are not namespaced (`would be ABTest` in above example`) so I'm finding the test with tags and then I'm jumping to the class file using vim-rails plugin's "alternate file" feature.

**Comment by mislav** [comment]
A feature has been added to the latest release which allows you to jump to fully qualified constant names such as `A::B` https://github.com/tmm1/ripper-tags/pull/44

The trick is to pass `--extra=q` argument. That will instruct ripper-tags to also output the `A::B` definition along with the usual `B` tag definition. This will increase the size of the tag file due to extra definitions, but it will allow you to jump to a fully qualified constant name if you selected it in code.

Let me know if it works.

**Comment by WojtekKruszewski** [comment]
@mislav Yes it works! Thank you Mislav.

**Comment by lowski** [comment]
Thanks @mislav, it's working for me as well.
