### ISSUE TITLE
Support GRTAGS

### ISSUE THREAD

**Issue by mmlac-bv** [tmm1/ripper-tags#53]
Gnu Global has the very useful ability to list the usages of a tag. Could this be supported in a future release?

**Comment by mislav** [comment]
I'm sorry; can you be more specific?

**Comment by mmlac-bv** [comment]
I'm sorry, of course.

CTags i.e. creates a TAGS file that maps  function foo()  ->  foo.rb line 35

That is great (and sufficient) for a 'go to the definition of what I am looking at' functionality.
GNU Global has a similar GTAGS file.

Now GNU Global in addition to that also has a G**R**TAGS file that tracks the inverse, where is a specific tag being used.

Foo.foo() -  foo() is being called in bar.rb line 89
f.foo()  - foo() is being called in baz.rb line 4


This allows gnu global then to do a lookup for 'where is the function I am currently on being used'.

I hope this clarifies it a bit more.

Thanks

**Comment by mislav** [comment]
Thanks for explaining. I'm afraid that this might be hard to pull of with static analysis of Ruby code. For instance, it's impossible to distinguish if `foo` is a reference to a variable or a call to `foo` function, since Ruby doesn't require parentheses for function invocations. Also, Ruby is highly dynamic, and supports invocations of method names constructed at runtime, such as `obj.send(my_method)` which would be a `foo` invocation if `my_method = :foo`.

Because of these reasons, we won't be building this functionality into ripper-tags at this time.

I suggest simply grepping for method names to find their points of invocation. I use The Silver Searcher for this: `ag -w foo`.
